version: 2
executorType: machine
stages:
  build:
    workDir: ~/poppler-deb
    steps:
      - type: checkout
      - type: shell
        name: Build image
        command: |
          cd trusty
          rm -rf out
          mkdir -p out
          docker-compose build
          docker-compose run poppler
      - type: shell
        name: Upload package
        command: |
            package=`ls ~/poppler-deb/trusty/out/`
            aws s3 cp ~/poppler-deb/trusty/out/$package s3://aspire-operations/binaries/aptly/$REPO/$package
